# languages.py
languages = {
    "English": {
        "title": "YouTube Video Downloader",
        "url_label": "YouTube URL:",
        "format_label": "Format:",
        "location_button": "Select Download Location",
        "download_button": "Download",
        "file_download_button": "Download from File",
        "speed_label": "Speed: 0 MB/s",
        "num_videos_label": "Videos: 0/0",
        "status_label": "",
        "fetch_success": "Video fetched successfully",
        "fetch_fail": "Failed to fetch video: ",
        "video_unavailable": "This video is unavailable",
        "no_video": "No video fetched to download",
        "download_complete": "Download completed",
        "download_fail": "Failed to download video: ",
        "all_downloads_complete": "All downloads completed",
        "error_reading_file": "Error reading file: ",
        "no_file_selected": "No file selected",
        "enter_url": "Please enter a YouTube URL",
        "tag_list_button": "Tag List",
        "no_file_found": "No downloaded files found",
        "tag_checkbox_text": "Tag after download",
        "rename_checkbox_text": "Rename M4A to MP3 After Download",
        "download_progressbar_label": "Download Progress:",
        "tagging_progressbar_label": "Tagging Progress:",
        "rename_button": "Rename m4a to mp3",
    },
    "Deutsch": {
        "title": "YouTube Video Downloader",
        "url_label": "YouTube URL:",
        "format_label": "Format:",
        "location_button": "Download Ort auswählen",
        "download_button": "Download",
        "file_download_button": "Download von einer Datei",
        "speed_label": "Geschwindigkeit: 0 MB/s",
        "num_videos_label": "Videos: 0/0",
        "status_label": "",
        "fetch_success": "Video erfolgreich abgerufen",
        "fetch_fail": "Fehler beim Abrufen des Videos: ",
        "video_unavailable": "Dieses Video ist nicht verfügbar",
        "no_video": "Kein Video zum Herunterladen abgerufen",
        "download_complete": "Download abgeschlossen",
        "download_fail": "Fehler beim Herunterladen des Videos: ",
        "all_downloads_complete": "Alle Downloads abgeschlossen",
        "error_reading_file": "Fehler beim Lesen der Datei: ",
        "no_file_selected": "Keine Datei ausgewählt",
        "enter_url": "Bitte gebe eine YouTube URL ein",
        "tag_list_button": "Liste Taggen",
        "no_file_found": "Keine heruntergeladenen Dateien gefunden",
        "tag_checkbox_text": "Nach Download taggen",
        "rename_checkbox_text": "M4A nach Download in MP3 umbenennen",
        "download_progressbar_label": "Download Fortschritt:",
        "tagging_progressbar_label": "Tagging Fortschritt:",
        "rename_button": "m4a in mp3 umbenennen",
    },
}
